kind: Secret
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: encryption-provider-config-shake256
  namespace: {{ include "resource.default.namespace" . }}
type: Opaque
apiVersion: v1
