# TEMPLATE-APP: This is set as a reasonable default, feel free to change.

name: {encryption-config-hasher}
namespace: kube-system
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/{encryption-config-hasher}
  tag: "[[ .Version ]]"
  pullPolicy: IfNotPresent

pod:
  user:
    id: 1000
  group:
    id: 1000
