name: encryption-config-hasher
namespace: kube-system
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

registry:
  domain: quay.io
image:
  name: giantswarm/encryption-config-hasher
  tag: "[[ .Version ]]"
  pullPolicy: IfNotPresent
